services:
  db:
    image: postgres:16
    container_name: houseshow_db
    environment:
      POSTGRES_USER: houseshow
      POSTGRES_PASSWORD: houseshow_password
      POSTGRES_DB: houseshow_dev
    ports:
      - "5432:5432"
    volumes:
      - houseshow_pgdata:/var/lib/postgresql/data

volumes:
  houseshow_pgdata:
